
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class MainFrame extends javax.swing.JFrame {
 
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        changeFont((Component) this.getContentPane(), new Font("Segoe UI", Font.PLAIN, 11));
    }
    
    private void changeFont(Component component, Font font) {
        component.setFont(font);
        if (component instanceof Container)
            for (Component child : ((Container) component).getComponents())
                changeFont(child, font);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaP2P");
        setPreferredSize(new Dimension(700, 400));
        setResizable(false);

        jTabbedPane1.add("Sending ", new HostPanel(this));
        jTabbedPane1.add("Receiving ", new PeerPanel(this));
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
